### ISSUE TITLE
WebAPI release (2.6.0) version not working

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/StandardizedAnalysisAPI#13]
When building an e released previous WebAPI version, a build error occurs due to downloading the latest version of the Standardized Analysis API package in maven.

**Comment by anthonysena** [comment]
@NEONKID - I've updated the tags on this repo to reflect the v1.0.0 release of this library that is referenced from WebAPI v2.6.0. From my testing this is fixed but could you please confirm? Thanks!

**Comment by NEONKID** [comment]
@anthonysena 
Thank you. Installation will proceed normally.
